version: '3.9'

services:    
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - backend/.env
    environment:
      - API_HOST=0.0.0.0
    ports:
      - "8080:8080"

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - ./frontend/.env
    ports:
      - "80:80"
